dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.1
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  fs:
    path: ../fs
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.10.0
