dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.1
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.5.1
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^2.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.13.0
