name: supabase
description: A supabase client for Toit
dependencies:
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.8.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^1.9.3
