// Copyright (C) 2024 Toitware ApS.
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.

/* Broker commands */
COMMAND-UPLOAD_ ::= 1
COMMAND-DOWNLOAD_ ::= 2
COMMAND-DOWNLOAD-PRIVATE_ ::= 3
COMMAND-UPDATE-GOAL_ ::= 4
COMMAND-GET-DEVICES_ ::= 5
COMMAND-NOTIFY-BROKER-CREATED_ ::= 6
COMMAND-GET-EVENTS_ ::= 7

COMMAND-GET-GOAL_ ::= 10
COMMAND-REPORT-STATE_ ::= 11
COMMAND-REPORT-EVENT_ ::= 12

COMMAND-POD-REGISTRY-DESCRIPTION-UPSERT_ ::= 100
COMMAND-POD-REGISTRY-ADD_ ::= 101
COMMAND-POD-REGISTRY-TAG-SET_ ::= 102
COMMAND-POD-REGISTRY-TAG-REMOVE_ ::= 103
COMMAND-POD-REGISTRY-DESCRIPTIONS_ ::= 104
COMMAND-POD-REGISTRY-DESCRIPTIONS-BY-IDS_ ::= 105
COMMAND-POD-REGISTRY-DESCRIPTIONS-BY-NAMES_ ::= 106
COMMAND-POD-REGISTRY-PODS_ ::= 107
COMMAND-POD-REGISTRY-PODS-BY-IDS_ ::= 108
COMMAND-POD-REGISTRY-POD-IDS-BY-REFERENCE_ ::= 109
COMMAND-POD-REGISTRY-DELETE-DESCRIPTIONS_ ::= 110
COMMAND-POD-REGISTRY-DELETE_ ::= 111

BROKER-COMMAND-TO-STRING ::= {
  COMMAND-UPLOAD_: "upload",
  COMMAND-DOWNLOAD_: "download",
  COMMAND-DOWNLOAD-PRIVATE_: "download-private",
  COMMAND-UPDATE-GOAL_: "update-goal",
  COMMAND-GET-DEVICES_: "get-devices",
  COMMAND-NOTIFY-BROKER-CREATED_: "notify-broker-created",
  COMMAND-GET-EVENTS_: "get-events",
  COMMAND-GET-GOAL_: "get-goal",
  COMMAND-REPORT-STATE_: "report-state",
  COMMAND-REPORT-EVENT_: "report-event",
  COMMAND-POD-REGISTRY-DESCRIPTION-UPSERT_: "pod-registry-description-upsert",
  COMMAND-POD-REGISTRY-ADD_: "pod-registry-add",
  COMMAND-POD-REGISTRY-TAG-SET_: "pod-registry-tag-set",
  COMMAND-POD-REGISTRY-TAG-REMOVE_: "pod-registry-tag-remove",
  COMMAND-POD-REGISTRY-DESCRIPTIONS_: "pod-registry-descriptions",
  COMMAND-POD-REGISTRY-DESCRIPTIONS-BY-IDS_: "pod-registry-descriptions-by-ids",
  COMMAND-POD-REGISTRY-DESCRIPTIONS-BY-NAMES_: "pod-registry-descriptions-by-names",
  COMMAND-POD-REGISTRY-PODS_: "pod-registry-pods",
  COMMAND-POD-REGISTRY-PODS-BY-IDS_: "pod-registry-pods-by-ids",
  COMMAND-POD-REGISTRY-POD-IDS-BY-REFERENCE_: "pod-registry-pod-ids-by-reference",
  COMMAND-POD-REGISTRY-DELETE-DESCRIPTIONS_: "pod-registry-delete-descriptions",
  COMMAND-POD-REGISTRY-DELETE_: "pod-registry-delete"
}
