-- This script was originally generated by the Schema Diff utility in pgAdmin 4, and
-- later changed by hand.

CREATE TABLE IF NOT EXISTS public.devices
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    config json DEFAULT NULL,
    CONSTRAINT devices_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.devices
    OWNER to postgres;

GRANT ALL ON TABLE public.devices TO anon;

GRANT ALL ON TABLE public.devices TO authenticated;

GRANT ALL ON TABLE public.devices TO postgres;

GRANT ALL ON TABLE public.devices TO service_role;
