dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.0
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.3.2
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.7.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^1.9.1
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.0.4
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
