dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.0
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.4.0
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  fs:
    path: tools/fs
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.9.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.1.0
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.1.1
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  artemis:
    url: github.com/toitware/toit-artemis
    version: ^0.1.0
  snapshot:
    path: tools/snapshot
  supabase:
    path: supabase
