dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.1
  artemis:
    url: github.com/toitware/toit-artemis
    version: ^0.1.1
  artemis-pkg:
    path: artemis-pkg-copy
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.1
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.5.1
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^2.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.13.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.3.4
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  semver:
    url: github.com/toitware/toit-semver
    version: ^1.1.0
  snapshot:
    path: tools/snapshot
  supabase:
    url: github.com/toitware/toit-supabase
    version: ^0.2.4
