dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.0
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.0.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.7.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^1.9.3
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.0.4
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
