dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.0
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.4.0
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.8.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^1.9.3
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.1.1
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  supabase:
    path: supabase
