dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.4.1
  artemis:
    path: ../..
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.11.0
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^2.6.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.16.2
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.11.0
  snapshot:
    path: ../snapshot
  supabase:
    url: github.com/toitware/toit-supabase
    version: ^0.3.1
