dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.3.1
  artemis:
    path: ../..
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.7.0
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^2.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.15.3
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.8.0
  snapshot:
    path: ../snapshot
  supabase:
    url: github.com/toitware/toit-supabase
    version: ^0.3.1
