dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.1
  artemis:
    path: ../..
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.1
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.6.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.13.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.3.4
  snapshot:
    path: ../snapshot
  supabase:
    url: github.com/toitware/toit-supabase
    version: ^0.2.5
