dependencies:
  artemis:
    path: ..
  artemis-pkg:
    path: ../artemis-pkg-copy
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.7.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.14.1
