name: CI

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        # Windows is not yet supported.
        # Avoid tests on macos for now. They are expensive.
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Jaguar and Toit
        shell: bash
        run: |
          if [[ "$RUNNER_OS" = "Windows" ]]; then
            BIN_EXTENSION=".exe"
          fi

          JAGUAR_VERSION=v1.7.0
          export "JAGUAR_VERSION=${JAGUAR_VERSION}"

          TOIT_SDK_DIR=$HOME/.cache/jaguar/sdk
          echo "TOIT_EXEC=$TOIT_SDK_DIR/bin/toit.run$BIN_EXTENSION" >> $GITHUB_ENV
          echo "TOITC_EXEC=$TOIT_SDK_DIR/bin/toit.compile$BIN_EXTENSION" >> $GITHUB_ENV
          echo "TPKG_EXEC=$TOIT_SDK_DIR/bin/toit.pkg$BIN_EXTENSION" >> $GITHUB_ENV

          export DOWNLOAD_DIR="${{ github.workspace }}/downloads"
          echo "DOWNLOAD_DIR=$DOWNLOAD_DIR" >> $GITHUB_ENV

          if [[ "$RUNNER_OS" = "Linux" ]]; then
            JAGUAR_FILE=jag_linux.tgz
          elif [[ "$RUNNER_OS" = "macOS" ]]; then
            JAGUAR_FILE=jag_macos.zip
          elif [[ "$RUNNER_OS" = "Windows" ]]; then
            JAGUAR_FILE=jag_windows.zip
          else
            echo "UNSUPPORTED RUNNER: $RUNNER_OS"
            exit 1
          fi

          JAGUAR_BASE_URL=https://github.com/toitlang/jaguar/releases

          if [[ $JAGUAR_VERSION = latest ]]; then
            echo "JAGUAR_URL=$JAGUAR_BASE_URL/latest/download/$JAGUAR_FILE" >> $GITHUB_ENV
          else
            echo "JAGUAR_URL=$JAGUAR_BASE_URL/download/$JAGUAR_VERSION/$JAGUAR_FILE" >> $GITHUB_ENV
          fi

      # Fetch the dependencies. Different for each platform.
      - name: Install dependencies - Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build mosquitto
          ninja --version
          cmake --version
      - name: Install dependencies - macOS
        if: runner.os == 'macOS'
        run: |
          brew install ninja
          ninja --version
          cmake --version
      - name: Install dependencies - Windows
        if: runner.os == 'Windows'
        run: |
          choco install ninja
          ninja --version
          cmake --version

      - uses: suisei-cn/actions-download-file@v1
        name: Download Toit
        with:
          url: ${{ env.JAGUAR_URL }}
          target: ${{ env.DOWNLOAD_DIR }}

      - name: Extract Jaguar - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          cd "$DOWNLOAD_DIR"
          tar x -f *.tgz
      - name: Extract Jaguar - macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          cd "$DOWNLOAD_DIR"
          unzip *.zip
      - name: Extract Jaguar - Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          cd "$DOWNLOAD_DIR"
          unzip *.zip

      - name: Setup Jaguar
        run: |
          cd "$DOWNLOAD_DIR"
          ./jag setup

      - name: Run cmake
        shell: bash
        run: |
          make rebuild-cmake
          cmake -DTOITC="$TOITC_EXEC" -DTOITPKG="$TPKG_EXEC" -DTOITRUN="$TOIT_EXEC" build

      - name: Install packages
        run: |
          make install-pkgs

      - name: Test
        run: |
          make test
