# Copyright (C) 2023 Toitware ApS. All rights reserved.

name: CI

on:
  push:

jobs:
  sign_artemis_macos:
    runs-on: macos-latest
    steps:
      - name: Import signing keychain
        uses: apple-actions/import-codesign-certs@v2
        with:
          keychain: signing_temp
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}

      - name: Notarize
        shell: bash
        run: |
          xcrun notarytool history \
              --apple-id "${{ secrets.AC_USERNAME }}" \
              --password "${{ secrets.AC_PASSWORD }}" \
              --team-id "33DS2ZRDST"
